/* tslint:disable */
/* eslint-disable */
/**
 * Axie Origin Data
 * This API about Axie Infinity: Origin will provide all the information you need about this NFT game 💪
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tony.duong.102@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

